aboutme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('yearrev.urls')),
]

yearrev/urls.py
from django.urls import path
from . import views
from . import views as core_views

urlpatterns =[
    path('',views.base,name='base'),
    path('anime/year/<int:pk>',views.anime,name='anime'),
    path('anime/year/',views.animeyear,name='animeyear'),
    path('anime/add',views.animeadd,name='animeadd'),
    path('anime/edit/<int:pk>/',views.editanime,name='editanime'),
    path('movie/year/<int:pk>',views.movie,name='movie'),
    path('movie/year/',views.moviesyear,name='movieyear'),
    path('movie/add',views.movieadd,name='movieadd'),
    path('game/year/2020', views.game, name='game2020'),
    path('game/year/2019', views.game2019, name='game2019'),
    path('game/year/2018', views.game2018, name='game2018'),
    path('game/year', views.gameyear, name='gameyear'),
    path('manga', views.manga, name='manga'),
    path('book', views.book, name='book'),
    path('drawing/year/',views.drawingyear,name='drawingyear'),
    path('drawing/year/<int:pk>',views.drawing,name='drawing'),
    path('cooking/year/',views.cookingyear,name='cookingyear'),

]

yearrev/models.py
from django.db import models
from django.contrib.auth.models import User


class Anime(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    )
    DATE = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
        (11, '11'),
        (12, '12'),
        (13, '13'),
        (14, '14'),
        (15, '15'),
        (16, '16'),
        (17, '17'),
        (18, '18'),
        (19, '19'),
        (20, '20'),
        (21, '21'),
        (22, '22'),
        (23, '23'),
        (24, '24'),
        (25, '25'),
        (26, '26'),
        (27, '27'),
        (28, '28'),
        (29, '29'),
        (30, '30'),
        (31, '31'),
    )
    MONTH = (
        (1, 'jan'),
        (2, 'feb'),
        (3, 'mar'),
        (4, 'apr'),
        (5, 'may'),
        (6, 'jun'),
        (7, 'jul'),
        (8, 'aug'),
        (9, 'sep'),
        (10, 'oct'),
        (11, 'nov'),
        (12, 'dec'),
    )
    YEAR = (
        (1, '2020'),
        (2, '2019'),
    )
    animeid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,unique=True)
    image = models.URLField(default='')
    rating = models.IntegerField(choices=RATING_CHOICES,default=1)
    startdate = models.IntegerField(choices=DATE ,default=1)
    startmonth = models.IntegerField(choices=MONTH,default=1)
    startyear = models.CharField(max_length=10,default=1)
    enddate = models.IntegerField(choices=DATE, default=1)
    endmonth = models.IntegerField(choices=MONTH, default=1)
    endyear = models.IntegerField(choices=YEAR, default=1)
    episode = models.IntegerField(default=12)

    def __str__(self):
        return self.title

class Movie(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    )
    DATE = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
        (11, '11'),
        (12, '12'),
        (13, '13'),
        (14, '14'),
        (15, '15'),
        (16, '16'),
        (17, '17'),
        (18, '18'),
        (19, '19'),
        (20, '20'),
        (21, '21'),
        (22, '22'),
        (23, '23'),
        (24, '24'),
        (25, '25'),
        (26, '26'),
        (27, '27'),
        (28, '28'),
        (29, '29'),
        (30, '30'),
        (31, '31'),
    )
    MONTH = (
        (1, 'jan'),
        (2, 'feb'),
        (3, 'mar'),
        (4, 'apr'),
        (5, 'may'),
        (6, 'jun'),
        (7, 'jul'),
        (8, 'aug'),
        (9, 'sep'),
        (10, 'oct'),
        (11, 'nov'),
        (12, 'dec'),
    )
    YEAR = (
        (1, '2020'),
        (2, '2021'),
    )
    movieid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,unique=True)
    image = models.URLField(default='')
    rating = models.IntegerField(choices=RATING_CHOICES,default=1)
    date = models.IntegerField(choices=DATE ,default=1)
    month = models.IntegerField(choices=MONTH,default=1)
    year = models.CharField(max_length=10,default=2020)

    def __str__(self):
        return self.title



class Manga(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    )

    MONTH = (
        (1, 'jan'),
        (2, 'feb'),
        (3, 'mar'),
        (4, 'apr'),
        (5, 'may'),
        (6, 'jun'),
        (7, 'jul'),
        (8, 'aug'),
        (9, 'sep'),
        (10, 'oct'),
        (11, 'nov'),
        (12, 'dec'),
    )
    YEAR = (
        (1, '2020'),
    )
    mangaid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,unique=True)
    image = models.URLField(default='')
    rating = models.IntegerField(choices=RATING_CHOICES,default=1)
    month = models.IntegerField(choices=MONTH,default=1)
    year = models.IntegerField(choices=YEAR,default=1)

    def __str__(self):
        return self.title

class Book(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    )

    MONTH = (
        (1, 'jan'),
        (2, 'feb'),
        (3, 'mar'),
        (4, 'apr'),
        (5, 'may'),
        (6, 'jun'),
        (7, 'jul'),
        (8, 'aug'),
        (9, 'sep'),
        (10, 'oct'),
        (11, 'nov'),
        (12, 'dec'),
    )
    YEAR = (
        (1, '2020'),
    )
    bookid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,unique=True)
    image = models.URLField(default='')
    rating = models.IntegerField(choices=RATING_CHOICES,default=1)
    month = models.IntegerField(choices=MONTH,default=1)
    year = models.IntegerField(choices=YEAR,default=1)

    def __str__(self):
        return self.title


class Drawing(models.Model):
    DATE = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
        (11, '11'),
        (12, '12'),
        (13, '13'),
        (14, '14'),
        (15, '15'),
        (16, '16'),
        (17, '17'),
        (18, '18'),
        (19, '19'),
        (20, '20'),
        (21, '21'),
        (22, '22'),
        (23, '23'),
        (24, '24'),
        (25, '25'),
        (26, '26'),
        (27, '27'),
        (28, '28'),
        (29, '29'),
        (30, '30'),
        (31, '31'),
    )

    MONTH = (
        (1, 'jan'),
        (2, 'feb'),
        (3, 'mar'),
        (4, 'apr'),
        (5, 'may'),
        (6, 'jun'),
        (7, 'jul'),
        (8, 'aug'),
        (9, 'sep'),
        (10, 'oct'),
        (11, 'nov'),
        (12, 'dec'),
    )
    YEAR = (
        (1, '2020'),
    )
    drawingid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,unique=True)
    model_pic = models.URLField(default='')
    date = models.IntegerField(choices=DATE, default=1)
    month = models.IntegerField(choices=MONTH,default=1)
    year = models.CharField(max_length=100,default="2020")

    def __str__(self):
        return self.title

yearrev/forms.py
from django import forms

from .models import Anime
from .models import Manga
from .models import Movie

from .models import Drawing
from .models import Book


class Animeform(forms.ModelForm):
    class Meta:
        model = Anime
        fields = ('title', 'image', 'rating', 'startdate', 'startmonth', 'startyear', 'enddate', 'endmonth', 'endyear')

class Movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'image', 'rating', 'date', 'month', 'year')

yearrev/views.py
from django.shortcuts import render, redirect

from yearrev.forms import *
from .models import *
from django.db.models import Q

def base(request):
    return render(request, 'base.html')

def anime(request,pk):
    query = pk
    if query is not None:
        lookups = Q(startyear__icontains=query)
        results =Anime.objects.filter(lookups)
        print(results)
        context = {'results': results, }
    return render(request, 'anime.html', context)

def animeadd(request):
    if request.method == 'GET':
        form = Animeform()
    else:
        form = Animeform(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.save()
            form = Animeform()
            return redirect('animeyear')
    return render(request, 'animeadd.html',{'form':form})

def movie(request,pk):
    query = pk
    if query is not None:
        lookups = Q(year__icontains=query)
        results = Movie.objects.filter(lookups)
        print(results)
        context = {'results': results, }
    return render(request, 'movie.html', context)

def movieadd(request):
    if request.method == 'GET':
        form = Movieform()
    else:
        form = Movieform(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.save()
            form =  Movieform()
            return redirect('movieyear')
    return render(request, 'movieadd.html',{'form':form})

def game(request):
    return render(request, 'game.html',{'game':game})

def manga(request):
    manga = Manga.objects.all()
    return render(request, 'manga.html',{'manga':manga})

def book(request):
    book = Book.objects.all()
    return render(request, 'book.html',{'book':book})

def moviesyear(request):
        return render(request, 'moviesyear.html')


def animeyear(request):
    return render(request, 'animeyear.html')
def gameyear(request):
    return render(request, 'gameyear.html')
def game2019(request):
    return render(request, 'gameyear2019.html')
def game2018(request):
    return render(request, 'gameyear2018.html')
def editanime(request):
    return render(request, 'animeedit.html')
def drawingyear(request):
    return render(request, 'drawingyear.html')

def drawing(request,pk):
    query = pk
    if query is not None:
        lookups = Q(year__icontains=query)
        results = Drawing.objects.filter(lookups)
        print(results)
        context = {'results': results, }
    return render(request, 'drawing2020.html', context)

def cookingyear(request):
    return render(request, 'cookingyear.html')

yearrev/templates/anime.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .row{
            margin-top: 100px;
            margin-bottom: 100px;
        }

    </style>
</head>
 {% load static %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'css/anime.css' %}">
<body>
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right"><i class="fa fa-bars"></i></a>
    <a href="{% url 'base' %}" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="{% url 'animeyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Anime</a>
    <a href="{% url 'movieyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Movie</a>
    <a href="{% url 'gameyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Game</a>
      <a href="{% url 'manga' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Manga</a>
       <a href="{% url 'book' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Book</a>
      <a href="{% url 'drawingyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Drawing</a>
    </div>
  </div>
</div>

<a href="{% url 'animeadd' %}"><h1 >ADD</h1></a>

<div class="containers">

{% for result in results %}
<div class="column" >
                <div class="box">
                            <div class="row" >
                                <div class="column" >
                                    <div class="imgbox">
                                    <img src="{{result.image}}"  width="200" height="300" >
                                    </div>
                                </div>
                                <div class="content">
                                    <h3>{{ result.title }}</h3>
                                    <br>
                                    <h3>Rating:</h3>
                                    <p>{{ result.rating }}</p>
                                    <h3>start date:</h3>
                                    <p>{{ result.startdate }}/{{ result.startmonth }}/{{ result.startyear }}</p>
                                    <h3>End date:</h3>
                                    <p>{{ result.enddate }}/{{ result.endmonth }}/{{ result.get_endyear_display }}</p>
                                    <h3>episodes:</h3>
                                    <p>{{ result.episode }}</p>
                                    <a href="#"><button>edit</button></a>
                                </div>
                            </div>
                </div>

        </div>
{% endfor %}
</div>


</body>
</html>

yearrev/templates/animeadd.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIE BUZZ</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/animeadd.css' %}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">




</head>
<body>
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right"><i class="fa fa-bars"></i></a>
    <a href="{% url 'base' %}" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="{% url 'animeyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Anime</a>
    <a href="{% url 'movieyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Movie</a>
    <a href="{% url 'gameyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Game</a>
      <a href="{% url 'manga' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Manga</a>
       <a href="{% url 'book' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Book</a>
      <a href="{% url 'drawingyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Drawing</a>
    </div>
  </div>
</div>


<form method="post">
    {% csrf_token %}
    <div class="login-box">
        <h1>ADD Anime</h1>
        <div class="textbox">
            <h2>Title:</h2>
            {{ form.title }}
        </div>
         <div class="textbox">
             <h2>image:</h2>
            {{ form.image }}
         </div>
         <div class="textbox">
             <h2>rating:</h2>
            {{ form.rating }}
         </div>
        <div class="textbox">
             <h2>episodes:</h2>
            {{ form.episode }}
         </div>
         <div class="textbox">
             <h2>start date:</h2>
            {{ form.startdate }}/{{ form.startmonth }}/{{ form.startyear }}
         </div>
         <div class="textbox">
             <h2>end date:</h2>
            {{ form.enddate }}/{{ form.endmonth }}/{{ form.endyear }}
         </div>

                   <div class="form-actions">
                       <button type="submit" class="btn" >Submit</button>
                  </div>

    </div>
</form>
</body>
</html>

yearrev/templates/animeedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

yearrev/templates/animeyear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/animeyear.css' %}">
</head>

<body>

    <a href="{% url 'anime' pk=2019 %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2019
    </a>
    <a href="{% url 'anime' pk=2020 %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2020
    </a>


</body>
</html>

yearrev/templates/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
</head>
<body>
    <div class="container">
        {% for book in book %}

        <div class="card">
            <div class="imgbox">
                <img src="{{ book.image }}" width="300" height="400" >
            </div>
            <div class="details">
                <h2>{{ book.title }}</h2>
                <h3>Rating:</h3>
                <p>{{ book.rating }}</p>
                <h3>read month and year:</h3>
                <p>{{ book.get_month_display }} {{ book.get_year_display }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

</body>
</html>

yearrev/templates/cookingyear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/gameyear.css' %}">

</head>

<body>

    <a href="{% url 'game2018' %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2018
    </a>
    <a href="{% url 'game2019' %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2019
    </a>
 <a href="{% url 'game2020' %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2020
    </a>


</body>
</html>

yearrev/templates/drawing2020.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/drawingyear.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right"><i class="fa fa-bars"></i></a>
    <a href="{% url 'base' %}" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="{% url 'animeyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Anime</a>
    <a href="{% url 'movieyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Movie</a>
    <a href="{% url 'gameyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Game</a>
      <a href="{% url 'manga' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Manga</a>
       <a href="{% url 'book' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Book</a>
      <a href="{% url 'drawingyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Drawing</a>
    </div>
  </div>
</div>
{% for result in results %}
<div class="container">
    <div class="box">
        <div class="imgbox">
            <img src="{{ result.model_pic }}">
        </div>
        <div class="content">
            <h2>{{result.title}}</h2>
            <p>{{ result.date }}/{{ result.month }}/{{ result.year }}</p>
        </div>
    </div>

</div>
{% endfor %}



</body>
</html>

yearrev/templates/drawingyear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/gameyear.css' %}">

</head>

<body>

    <a href="{% url 'drawing' pk=2018 %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2018
    </a>
    <a href="{% url 'drawing' pk=2019 %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2019
    </a>
 <a href="{% url 'drawing' pk=2020 %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2020
    </a>


</body>
</html>

yearrev/templates/gameyear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/gameyear.css' %}">

</head>

<body>

    <a href="{% url 'game2018' %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2018
    </a>
    <a href="{% url 'game2019' %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2019
    </a>
 <a href="{% url 'game2020' %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2020
    </a>


</body>
</html>

yearrev/templates/gameyear2018.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>2018</h2>

</body>
</html>

yearrev/templates/gameyear2019.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .row{
            margin-top: 100px;
            margin-bottom: 100px;
        }
    </style>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/game2019.css' %}">

</head>

<body>

    <section class="split">
        <div class="screen">
            <div class="content">
                <h2>Assassins Creed Odyssey</h2>

                <h3>Rating:</h3>
                    <p>10</p>
                 <h3>play month and year:</h3>
                    <p>FEB 2019</p>


            </div>
        </div>
        <div class="screen">
            <div class="content">
                <h2>Life Is Strange 2</h2>

                <h3>Rating:</h3>
                    <p>9</p>
                 <h3>play month and year:</h3>
                    <p>DEC 2019</p>


            </div>
        </div>
        <div class="screen">
            <div class="content">
                <h2>Witcher 3 wild hunt</h2>

                <h3>Rating:</h3>
                    <p>10</p>
                 <h3>play month and year:</h3>
                    <p>Feb 2020</p>


            </div>
        </div>
        <div class="screen">
            <div class="content">
                <h2>Pubg</h2>

                <h3>Rating:</h3>
                    <p>10</p>
                 <h3>play month and year:</h3>
                    <p>march 2018 to jan 2020</p>


            </div>
        </div>
        <div class="screen">
            <div class="content">
                <h2>WWE2K19</h2>

                <h3>Rating:</h3>
                    <p>9</p>
                 <h3>play month and year:</h3>
                    <p>Jan 2020</p>


            </div>
        </div>

    </section>

</body>
</html>

yearrev/templates/manga.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/manga.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right"><i class="fa fa-bars"></i></a>
    <a href="{% url 'base' %}" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="{% url 'animeyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Anime</a>
    <a href="{% url 'movieyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Movie</a>
    <a href="{% url 'gameyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Game</a>
      <a href="{% url 'manga' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Manga</a>
       <a href="{% url 'book' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Book</a>
      <a href="{% url 'drawingyear' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Drawing</a>
    </div>
  </div>
</div>
    <div class="container">
        {% for manga in manga %}

        <div class="card">
            <div class="imgbox">
                <img src="{{ manga.image }}" width="300" height="400" >
            </div>
            <div class="details">
                <h2>{{ manga.title }}</h2>
                <h3>Rating:</h3>
                <p>{{ manga.rating }}</p>
                <h3>read month and year:</h3>
                <p>{{ manga.get_month_display }} {{ manga.get_year_display }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

</body>
</html>

yearrev/templates/moviesyear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/moviesyear.css' %}">
</head>

<body>
    <a href="{% url 'movie' pk=2020 %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2020
    </a>
    <a href="{% url 'movie' pk=2021 %}">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        2021
    </a>


</body>
</html>